# Generated by Django 5.0.2 on 2024-02-24 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produtos',
            old_name='descrição',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='produtos',
            old_name='Quantidade',
            new_name='quantidade',
        ),
    ]
